# Generated by Django 5.0.3 on 2024-03-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
